
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'VHMessengerKit_Example' do
  
  use_frameworks!
  
  pod 'VHMessengerKit', :path => '../'
  pod 'FLAnimatedImage'
  pod 'SDWebImage'
end

post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            end
         end
     end
  end
